### ISSUE TITLE
ERROR : Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by FrankSays** [mbkumar/pycdt#8]
I have download the latest anaconda3(python 3.8) and pycdt(2.0.5), when I try to run the example code, there is a werid ERROR： Illegal instruction (core dumped)
I tried the code on both super computing(Linux AMD roma) and my workstation(Ubuntu18 Intel)

The code:
from pymatgen.ext.matproj import MPRester
with MPRester() as mpr:
    mgo_struct = mpr.get_structure_by_material_id('mp-1265')
from pycdt.core.defectsmaker import DefectChargerInsulator
defect_charger = DefectChargerInsulator(mgo_struct)
mg_vac_charges = defect_charger.get_charges('vacancy',site_specie='Mg')

from pycdt.core.defectsmaker import ChargedDefectsStructures
charged_defects_structs = ChargedDefectsStructures(mgo_struct)
from pycdt.utils.vasp import DefectRelaxSet
defect_struct = charged_defects_structs.get_ith_supercell_of_defect_type(0, 'vacancies')
vasp_input = DefectRelaxSet(defect_struct) # defect_struct is defectsupercell
vasp_input.write_input(output_dir)
vasp_input = DefectRelaxSet(defect_struct, potcar_functional="PBE")
user_settings = {'potcar_functional': 'PBE','user_incar_settings': {'EDIFFG': -1e-3, 'EDIFF': 1e-8, 'LASPH': True}}
vasp_input = DefectRelaxSet(defect_struct,**user_settings)

**Comment by mbkumar** [comment]
Could you run the code line by line in jupyter notebook and see where the code is failing. For me all the lines are working fine. The only issue I encountered from your code is **output_dir** is not defined.

**Comment by FrankSays** [comment]
Thank you for answering me. I tried my laptop(win10 intel) today and also only output_dir problem. However the linux system could have the problem that #The kernel appears to have died. It will restart automatically.#(ubuntu18 intel juputernotebook). if it is possible for you to check the linux system ?

**Comment by mbkumar** [comment]
The code was developed on linux and I ran your code on linux. The issue seems something else. Did you install jupyter, ipython, and notebook in the anaconda virtual environment? That could be one issue I can think of? 

Anyhow, the issue you raised is not related to pycdt. Please contact your sysadmin or local linux guru to get the issue resolved.
