### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by utf** [mbkumar/pycdt#9]
I can see that there have been no new commits to PyCDT for ~1 year. Is the project still actively maintained/will there be any updates?

**Comment by mbkumar** [comment]
pycdt has been ported to pymatgen. And also the current code is mature and
doesn't need much work unless new features are wanted.
Unfortunately, all the original developers moved on to other stuff to
implement new features. I may get back to pycdt development next year
depending on the funding situation. We meet once in a while to work on bug
fixes, which we did last year.

Hope this info helps.

Bharat Medasani

Engineer
Princeton Plasma Physics Lab (PPPL)

**Comment by utf** [comment]
Ok, great. Thanks.
